services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: studentstorefront
      POSTGRES_USER: student
      POSTGRES_PASSWORD: CHANGE_THIS
    ports:
      - "5432:5432"
    volumes:
      - db_persistency:/var/lib/postgresql

volumes:
  db_persistency:
